name = "familiada"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "MAINT_KV"
id = "a23c036852434c5da77287d82973f183"

[vars]
SUPABASE_URL = "https://api.familiada.online"
